const CurrenciesObject = {
        AFN:"Afghan Afghani", 
        ALL:"Albanian Lek", 
        DZD:"Algerian Dinar", 
        AOA:"Angolan Kwanza", 
        ARS:"Argentine Peso", 
        AMD:"Armenian Dram", 
        AWG:"Aruban Florin", 
        AUD:"Australian Dollar", 
        AZN:"Azerbaijani Manat", 
        BSD:"Bahamian Dollar", 
        BHD:"Bahraini Dinar", 
        BDT:"Bangladeshi Taka", 
        BYR:"Belarusian Ruble",
        BHD:"Belize Dollar",
        BMD:"Bermudan Dollar",
        BTN:"Bhutanese Ngultrum",
        BTC:"Bitcoin",
        BOB:"Bolivian Boliviano",
        BHD:"Botswanan Pula",
        BRL:"Brazilian Real",
        BND:"Brunei Dollar",
        BGN:"Bulgarian Lev",
        BIF:"Burundian Franc",
        XPF:"CFP Franc",
        KHR:"Cambodian riel",
        CAD:"Canadian Dollar",
        CVE:"Cape Verdean Escudo",
        KYD:"Cayman Islands Dollar",
        XAF:"Central African CFA franc",
        CLP:"Chilean Peso",
        CLF:"Chilean Unit of Account (UF)",
        CVE:"Chinese Yuan",
        COP:"Colombian Peso",
        KMF:"Comorian Franc",
        CDF:"Congolese Franc",
        CRC:"Costa Rican Colón",
        HRK:"Croatian Kuna",
        CUP:"Cuban Peso",
        CRC:"Czech Koruna",
        DKK:"Danish Krone",
        DJF:"Djiboutian Franc",
        DOP:"Dominican Peso",
        XCD:"East Caribbean Dollar",
        EGP:"Egyptian Pound",
        ETB:"Ethiopian Birr",
        EUR:"Euro",
        FJD:"Fijian Dollar",
        GMD:"Gambian dalasi",
        GEL:"Georgian Lari",
        GHS:"Ghanaian Cedi",
        GTQ:"Guatemalan Quetzal",
        GNF:"Guinean Franc",
        GGP:"Guernsey Pound",
        GYD:"Guyanaese Dollar",
        HTG:"Haitian Gourde",
        HNL:"Honduran Lempira",
        HKD:"Hong Kong Dollar",
        HUF:"Hungarian Forint",
        ISK:"Icelandic Króna",
        INR:"Indian Rupee",
        IDR:"Indonesian Rupiah",
        IRR:"Iranian Rial",
        IQD:"Iraqi Dinar",
        ILS:"Israeli New Shekel",
        JMD:"Jamaican Dollar",
        JPY:"Japanese Yen",
        JEP:"Jersey Pound",
        JOD:"Jordanian Dinar",
        KZT:"Kazakhstani Tenge",
        KES:"Kenyan Shilling",
        KWD:"Kuwaiti Dinar",
        KGS:"Kyrgystani Som",
        LAK:"Laotian Kip",
        LVL:"Latvian Lats",
        LBP:"Lebanese Lira",
        LSL:"Lesotho loti",
        LRD:"Liberian Dollar",
        LYD:"Libyan Dinar",
        MOP:"Macanese Pataca",
        MKD:"Macedonian Denar",
        MGA:"Malagasy Ariary",
        MWK:"Malawian Kwacha",
        LSL:"Malaysian Ringgit",
        MVR:"Maldivian Rufiyaa",
        IMP:"Manx Pound",
        MUR:"Mauritian Rupee",
        MXN:"Mexican Peso",
        MDL:"Moldovan Leu",
        MAD:"Moroccan Dirham",
        MZN:"Mozambican metical",
        MMK:"Myanmar Kyat",
        NAD:"Namibian dollar",
        NPR:"Nepalese Rupee",
        ANG:"Netherlands Antillean Guilder",
        TWD:"New Taiwan dollar",
        NZD:"New Zealand Dollar",
        NIO:"Nicaraguan Córdoba",
        NGN:"Nigerian Naira",
        KPW:"North Korean Won",
        NOK:"Norwegian Krone",
        OMR:"Omani Rial",
        PKR:"Pakistani Rupee",
        PAB:"Panamanian Balboa",
        PGK:"Papua New Guinean Kina",
        PYG:"Paraguayan Guarani",
        PEN:"Peruvian Nuevo Sol",
        PHP:"Philippine peso",
        PLN:"Poland złoty",
        GBP:"British Pound ",
        QAR:"Qatari Rial",
        RON:"Romanian Leu",
        RUB:"Russian Ruble",
        RWF:"Rwandan franc",
        SVC:"Salvadoran Colón",
        SAR:"Saudi Riyal",
        RSD:"Serbian Dinar",
        SCR:"Seychellois Rupee",
        SLL:"Sierra Leonean Leone",
        XAG:"Silver (troy ounce)",
        SGD:"Singapore Dollar",
        SBD:"Solomon Islands Dollar",
        SOS:"Somali Shilling",
        ZAR:"South African Rand",
        KRW:"South Korean won",
        VEF:"Venezuelan Bolivar",
        LKR:"Sri Lankan Rupee",
        SHP:"St. Helena Pound",
        SDG:"Sudanese pound",
        SRD:"Surinamese Dollar",
        SZL:"Swazi Lilangeni",
        SEK:"Swedish Krona",
        CHF:"Swiss Franc",
        SYP:"Syrian Pound",
        TJS:"Tajikistani Somoni",
        TZS:"Tanzanian Shilling",
        THB:"Thai Baht",
        TTD:"Trinidad &amp; Tobago Dollar",
        TND:"Tunisian Dinar",
        TRY:"Turkish lira",
        TMT:"Turkmenistani manat",
        UGX:"Ugandan Shilling",
        UAH:"Ukrainian hryvnia",
        AED:"United Arab Emirates Dirham",
        USD:"United States Dollar",
        UYU:"Uruguayan Peso",
        UZS:"Uzbekistani Som",
        VUV:"Vanuatu Vatu",
        VEF:"Venezuelan Bolivar",
        VND:"Vietnamese Dong",
        YER:"Yemeni Rial",
        ZMW:"Zambian Kwacha"
};

const DefaultValues = (defaultCurrency, fromCurreny, toCurrency)=> {
    if(defaultCurrency !== "" && fromCurreny == "" && toCurrency === ""){
        localStorage.setItem("defaultCurrency", defaultCurrency);
    }
    else if (fromCurreny !== "" && toCurrency !== ""){
        localStorage.setItem("fromCurreny", fromCurreny);
        localStorage.setItem("toCurrency", toCurrency);
    }
    else {
       if(localStorage.getItem("defaultCurrency") === null){
           localStorage.setItem("defaultCurrency", "RUB");
           localStorage.setItem("fromCurreny", "RUB");
           localStorage.setItem("toCurrency", "USD");
        }

        return [localStorage.getItem("defaultCurrency"),
                localStorage.getItem("fromCurreny"), 
                localStorage.getItem("toCurrency"),
            ];
    }
}
const CurrenciesOptions = (container_id) => {
    const container = document.getElementById(container_id);
    let content = ``;
    for(let [key, value] of Object.entries(CurrenciesObject)){
       
            content += `<option value="${key}">${value}</option>`
        }
    container.innerHTML = content;
};

export {DefaultValues,  CurrenciesOptions, CurrenciesObject};
